import re
import psycopg2
import configparser
import pickle

config = configparser.ConfigParser()
config.read('../../config.ini')


def setconnection(config):
	dbconnection = psycopg2.connect(user=config['db']['DBUSER'], host=config['db']['DBHOST'],
	                                port=config['db']['DBPORT'], database=config['db']['DBNAME'],
	                                password=config['db']['DBPASS'])
	dbconnection.set_isolation_level(psycopg2.extensions.ISOLATION_LEVEL_AUTOCOMMIT)
	
	return dbconnection

dbconnection = setconnection(config)
# dbconnection.set_isolation_level(psycopg2.extensions.ISOLATION_LEVEL_AUTOCOMMIT)
cursor = dbconnection.cursor()

# ocd_authors.txt generated by sending OCD.ABBREVIATIONS.PDF to https://pdftables.com
ocd = '../../../HipparchiaData/lexica/ocd_authors.txt'
outdir = '../../../HipparchiaServer/server/lexica/'

with open(ocd) as f:
	content = f.read().splitlines()

entries = []

for c in content:
	entries.append(c.split('\t'))

query = 'SELECT shortname FROM authors ORDER BY shortname ASC'
cursor.execute(query)
shortnames = cursor.fetchall()

# this is a pretty rough guess: take an authorname, try to match it to the second column of the OCD data,
# then say that the abbreviation in column 1 is the abbreviation for this author. um: maybe.
# this is more 'in progress' than it is actually useful

abbreviations = {}
for s in shortnames:
	sn = s[0]
	try:
		if sn[-1] == '':
			sn = sn[:-1]
	except:
		pass
	
	# print(sn)
	
	for e in entries:
		try:
			if re.search(re.escape(sn), e[1]) is not None:
				abbreviations[e[0]] = e[1]
		except:
			# there was no e[1]
			pass
		
# pickle.dump(abbreviations, open( outdir+'abbreviations.p', 'wb' ) )
