-- use this to (re)initialize by hand

-- \connect postgres

DROP ROLE IF EXISTS hippa_wr;

CREATE ROLE hippa_wr LOGIN
  ENCRYPTED PASSWORD 'CHANGEME'
  NOSUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;

DROP ROLE IF EXISTS hippa_rd;

CREATE ROLE hippa_rd LOGIN
  ENCRYPTED PASSWORD 'CHANGEME'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

DROP DATABASE IF EXISTS "hipparchiaDB";
CREATE DATABASE "hipparchiaDB" WITH OWNER = hippa_wr ENCODING = 'UTF8' TABLESPACE = pg_default CONNECTION LIMIT = -1;
ALTER DATABASE "hipparchiaDB" OWNER TO hippa_wr;